### ISSUE TITLE
[To-Do] Trainning Dummies

### ISSUE THREAD

**Issue by EPuncker** [opentibiabr/otservbr-global#321]
- [ ] adicionar as exercise weapons no store por 25 coins cada, no momento o store não suporta isso, pois ele não vende item com cargas, apenas por quantidade
- [ ] verificar se a checagem de vocation na formula está contando as vocation promoted
- [ ] uma tabela melhor pro script?
- [ ] If you do any action while attacking the Dummy, such as moving, casting spells or using items, the training will automatically stop.
- [ ] Characters can only use the Exercise Dummy once every 30 seconds to avoid quick alternations between using the weapons and casting spells.
- [ ] (dummies do ID 32143 ao 32148) The expert Dummies offer an additional 10% in skill advance speed, however
- [ ] os dummies que dão 10% de bonus só podem ser usados por UMA PESSOA POR VEZ
- [ ] adicionar os expert dummies ID 32143 ao 32148 no store por 900 coins cada
- [ ] adicionar ,32124,32125,32126,32127,32128,32129 no events/script/player.lua

- [x] sim todas vocations podem usar as weapons que quiserem, eu chequei, a única coias q muda é a fórmula, um knight usando uma exercise rod ainda vai upar ML lentamente, assim como um mago usando um exercise axe

**Comment by cellss** [comment]
- [x]  adicionar as exercise weapons no store por 25 coins cada, no momento o store não suporta isso, pois ele não vende item com cargas, apenas por quantidade

- [x]  verificar se a checagem de vocation na formula está contando as vocation promoted

> The formula to promoted is the same...

- [ ] uma tabela melhor pro script?

> what?

- [x]  If you do any action while attacking the Dummy, such as moving, casting spells or using items, the training will automatically stop.

> Only if you move, is that not right?

- [ ]  Characters can only use the Exercise Dummy once every 30 seconds to avoid quick alternations between using the weapons and casting spells.

> You can use it anytime.

- [x] (dummies do ID 32143 ao 32148) The expert Dummies offer an additional 10% in skill advance speed, however

> 32143 rotateTo  32144, 32145 rotateTo 32146 and 32147 rotateTo 32148...  to do

- [ ] os dummies que dão 10% de bonus só podem ser usados por UMA PESSOA POR VEZ

> 32143 rotateTo  32144, 32145 rotateTo 32146 and 32147 rotateTo 32148...  to do

- [x]  adicionar os expert dummies ID 32143 ao 32148 no store por 900 coins cada

> 32143 rotateTo  32144, 32145 rotateTo 32146 and 32147 rotateTo 32148...  to do

- [x] adicionar ,32124,32125,32126,32127,32128,32129 no events/script/player.lua

- [ ] sim todas vocations podem usar as weapons que quiserem, eu chequei, a única coias q muda é a fórmula, um knight usando uma exercise rod ainda vai upar ML lentamente, assim como um mago usando um exercise axe

> there is a new formula after the PR opentibiabr/otservbr-global#579 and I didn't get the point here...

....
